# Etapa de build (Maven + Java 17)
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

# Cacheo de dependencias
COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline

# Código y build
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre-alpine
RUN apk add --no-cache curl
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]